/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_lpadc.h"
#include "fsl_spc.h"
#include "fsl_vref.h"
#include "fsl_gpio.h"
#include "fsl_ctimer.h"
#include "fsl_dac.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define LP_FLEXCOMM4_PERIPHERAL ((LPUART_Type *) LP_FLEXCOMM4)
/* Definition of the clock source frequency */
#define LP_FLEXCOMM4_CLOCK_SOURCE 12000000UL
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* ADC0 interrupt vector ID (number). */
#define ADC0_IRQN ADC0_IRQn
/* ADC0 interrupt handler identifier. */
#define ADC0_IRQHANDLER ADC0_IRQHandler
/* Command 1 - cmd0 */
#define ADC0_CMD0 1U
/* Trigger 0 - trig0 */
#define ADC0_TRIG0 0U
/* Definition of peripheral ID */
#define VREF0_PERIPHERAL VREF0
/* Alias for GPIO0 peripheral */
#define GPIO0_GPIO GPIO0
/* Alias for PORT0 */
#define GPIO0_PORT PORT0
/* GPIO0 interrupt vector ID (number). */
#define GPIO0_INT_0_IRQN GPIO00_IRQn
/* GPIO0 interrupt vector priority. */
#define GPIO0_INT_0_IRQ_PRIORITY 1
/* GPIO0 interrupt handler identifier. */
#define GPIO0_INT_0_IRQHANDLER GPIO00_IRQHandler
/* GPIO0 interrupt vector ID (number). */
#define GPIO0_INT_1_IRQN GPIO01_IRQn
/* GPIO0 interrupt vector priority. */
#define GPIO0_INT_1_IRQ_PRIORITY 1
/* GPIO0 interrupt handler identifier. */
#define GPIO0_INT_1_IRQHANDLER GPIO01_IRQHandler
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 1200000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 833UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 3 ID */
#define CTIMER0_MATCH_3_CHANNEL kCTIMER_Match_3
/* BOARD_InitPeripherals defines for DAC0 */
/* Definition of peripheral ID */
#define DAC0_PERIPHERAL DAC0
/* DAC0 interrupt vector ID (number). */
#define DAC0_IRQN DAC0_IRQn
/* DAC0 interrupt handler identifier. */
#define DAC0_IRQHANDLER DAC0_IRQHandler
/* Definition of peripheral ID */
#define CTIMER1_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER1_TICK_FREQ 10000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER1_TICK_PERIOD 100UL
/* Definition of PWM period channel. */
#define CTIMER1_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER1_MATCH_0_CHANNEL kCTIMER_Match_0
/* CTIMER1 interrupt vector ID (number). */
#define CTIMER1_TIMER_IRQN CTIMER1_IRQn
/* CTIMER1 interrupt vector priority. */
#define CTIMER1_TIMER_IRQ_PRIORITY 2
/* BOARD_InitPeripherals defines for DAC1 */
/* Definition of peripheral ID */
#define DAC1_PERIPHERAL DAC1
/* DAC1 interrupt vector ID (number). */
#define DAC1_IRQN DAC1_IRQn
/* DAC1 interrupt handler identifier. */
#define DAC1_IRQHANDLER DAC1_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpuart_config_t LP_FLEXCOMM4_config;
extern const lpadc_config_t ADC0_config;
extern lpadc_conv_command_config_t ADC0_commandsConfig[1];
extern lpadc_conv_trigger_config_t ADC0_triggersConfig[1];
extern const ctimer_config_t CTIMER0_config;
extern const ctimer_match_config_t CTIMER0_Match_3_config;
/* LPDAC configuration */
extern const dac_config_t DAC0_config;
extern const ctimer_config_t CTIMER1_config;
extern const ctimer_match_config_t CTIMER1_Match_0_config;
/* LPDAC configuration */
extern const dac_config_t DAC1_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
  /* Single callback function declaration */
extern void ctimer1_match0_callback(uint32_t flags);
extern ctimer_callback_t CTIMER1_callback[];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
