/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
 * Generated on: 25-Nov-2025 20:31:36
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 32
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2025b\extern\include\tmwtypes.h 
 */
const uint16_t pasabajo_8k_length = 32;
const q15_t pasabajo_8k[32] = {
      236,   -318,    400,   -470,    519,   -534,    500,   -402,    224,
       55,   -464,   1055,  -1934,   3381,  -6439,  20576,  20576,  -6439,
     3381,  -1934,   1055,   -464,     55,    224,   -402,    500,   -534,
      519,   -470,    400,   -318,    236
};
