/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
 * Generated on: 26-Nov-2025 16:43:29
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 124
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s29,30 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2025b\extern\include\tmwtypes.h 
 */
const uint16_t pasabajo_48k_length = 124;
const q15_t pasabajo_48k[124] = {
      -44,    -17,     18,     52,     77,     87,     78,     50,      8,
      -41,    -84,   -113,   -118,    -97,    -51,     11,     76,    129,
      158,    153,    112,     42,    -44,   -128,   -190,   -214,   -191,
     -122,    -19,     98,    204,    272,    285,    234,    123,    -27,
     -186,   -319,   -393,   -384,   -285,   -108,    115,    340,    514,
      593,    543,    358,     58,   -308,   -668,   -939,  -1042,   -914,
     -523,    124,    979,   1957,   2946,   3827,   4488,   4841,   4841,
     4488,   3827,   2946,   1957,    979,    124,   -523,   -914,  -1042,
     -939,   -668,   -308,     58,    358,    543,    593,    514,    340,
      115,   -108,   -285,   -384,   -393,   -319,   -186,    -27,    123,
      234,    285,    272,    204,     98,    -19,   -122,   -191,   -214,
     -190,   -128,    -44,     42,    112,    153,    158,    129,     76,
       11,    -51,    -97,   -118,   -113,    -84,    -41,      8,     50,
       78,     87,     77,     52,     18,    -17,    -44
};
