/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
 * Generated on: 26-Nov-2025 17:08:18
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 58
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s30,30 -> [-5.000000e-01 5.000000e-01)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
const uint16_t pasabajo_22k_length = 58;
const q15_t pasabajo_22k[58] = {
     -126,      0,    157,    180,     13,   -206,   -250,    -34,    263,
      340,     68,   -332,   -460,   -120,    420,    626,    202,   -540,
     -876,   -338,    725,   1304,    600,  -1082,  -2263,  -1298,   2240,
     6928,  10244,  10244,   6928,   2240,  -1298,  -2263,  -1082,    600,
     1304,    725,   -338,   -876,   -540,    202,    626,    420,   -120,
     -460,   -332,     68,    340,    263,    -34,   -250,   -206,     13,
      180,    157,      0,   -126
};
