/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
 * Generated on: 26-Nov-2025 17:07:50
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 42
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s30,30 -> [-5.000000e-01 5.000000e-01)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
const uint16_t pasabajo_16k_length = 42;
const q15_t pasabajo_16k[42] = {
     -133,    155,    236,   -122,   -356,     33,    475,    127,   -571,
     -368,    613,    704,   -560,  -1156,    346,   1785,    175,  -2828,
    -1575,   5892,  13512,  13512,   5892,  -1575,  -2828,    175,   1785,
      346,  -1156,   -560,    704,    613,   -368,   -571,    127,    475,
       33,   -356,   -122,    236,    155,   -133
};
