/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
 * Generated on: 26-Nov-2025 17:08:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 114
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s29,30 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
const uint16_t pasabajo_44k_length = 114;
const q15_t pasabajo_44k[114] = {
      -52,    -20,     21,     61,     89,     95,     76,     33,    -23,
      -78,   -118,   -130,   -107,    -53,     22,     98,    155,    175,
      149,     80,    -17,   -120,   -200,   -233,   -206,   -120,      8,
      146,    259,    313,    287,    179,     10,   -180,   -343,   -431,
     -410,   -274,    -44,    229,    477,    628,    627,    449,    114,
     -317,   -745,  -1053,  -1130,   -894,   -314,    579,   1691,   2879,
     3976,   4818,   5275,   5275,   4818,   3976,   2879,   1691,    579,
     -314,   -894,  -1130,  -1053,   -745,   -317,    114,    449,    627,
      628,    477,    229,    -44,   -274,   -410,   -431,   -343,   -180,
       10,    179,    287,    313,    259,    146,      8,   -120,   -206,
     -233,   -200,   -120,    -17,     80,    149,    175,    155,     98,
       22,    -53,   -107,   -130,   -118,    -78,    -23,     33,     76,
       95,     89,     61,     21,    -20,    -52
};
